#THIS ALLOWS  FOR THE THREE SEPARATE MODULES- OVERHEADS, PROFIT_LOSS, CASH_ON_HAND TO BE IMPORTED INTO THIS MAINSOLUTION.PY
import overheads, profit_loss, cash_on_hand


def main():

    """
    
    -INITIATES EXECUTION OF THREE SEPARATE FUNCTIONS- 
    "function_overheads()", "profitAndloss_function()", "cashOnHand_function()"
    EACH LOCATED IN THEIR RESPECTIVE MODULES

    -FUNCTION IDENTIFIES OVERHEAD CATEGORY WITH THE HIGHEST PERCENTAGE, 
    CALCULATES TO DETERMINE CASH DEFICIT OR CASH SURPLUS, WITH TOP THREE HIGHEST CASH DEFICIT DAYS 
    CALCULATES TO DETERMINE NET PROFIT DEFICIT OR NET PROFIT SURPLUS, WITH TOP THREE NET PROFIT DEFICIT DAYS
    
    -NO INPUT PARAMETERS REQUIRED
    -OUTPUT IS WRITTEN INTO SUMMARY_REPORT.TXT

    """
    
    #WRITES REQUIRED HEADERS IN SUMMARY_REPORT.TXT
    filename = 'Summary_report.txt'
    file = open(filename, 'w')
    file.write('Summary Report\n==============================\n')

    #FUNCTION_OVERHEADS() IN OVERHEADS MODULE CALLED TO BE EXECUTED, TO CALCULATE, AND WRITE HIGHEST OVERHEAD INTO SUMMARYREPORT.TXT
    file.write(overheads.function_overheads()) 

    #PROFITANDLOSS_FUNCTION() IN PROFITS AND LOSS MODULE CALLED TO BE EXECUTED, 
    #TO CALCULATE, AND WRITE NET PROFIT DEFICITS/ SURPLUS INTO SUMMARYREPORT.TXT
    file.write(profit_loss.profitAndloss_function()+ "\n")

    #CASHONHAND_FUNCTION() IN CASH ON HAND MODULE CALLED TO BE EXECUTED,
    #TO CALCULATE, AND WRITE CASH DEFICITS/HIGHEST SURPLUS INTO SUMMARYREPORT.TXT
    file.write(cash_on_hand.cashOnHand_function())

main () 




